[package]
name = "bevy_mod_xr_backends"
version = "0.1.0"
edition = "2021"
description = "Community crate for OpenXR in Bevy"
repository = "https://github.com/awtterpip/bevy_oxr"
license = "MIT/Apache-2.0"

[dependencies]
bevy_mod_openxr.path = "./crates/bevy_openxr"
bevy_mod_xr.path = "./crates/bevy_xr"
bevy.workspace = true

[workspace]
members = ["crates/*", "crates/bevy_openxr/examples/android"]

[workspace.dependencies]
bevy = "0.13.0"
