[package]
name = "bevy_xr_utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy.workspace = true
bevy_mod_xr = { path = "../bevy_xr", version = "0.1.0-rc1" }
bevy_mod_openxr = { path = "../bevy_openxr", version = "0.1.0-rc1" }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
openxr = "0.18.0"
